sudo: required
language: node_js
os:
  - linux
  - osx
node_js:
  - "5.9"
env:
  - CXX=g++-4.8
addons:
  artifacts:
    paths:
    - ./releases
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script:
  - npm run build
  - npm run lint
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run package-osx; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run package-linux; fi
