version: '1.0.{build}'

platform:
  - x64

cache:
  - node_modules -> package.json
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

install:
  - ps: Install-Product node 5 x64
  - git reset --hard HEAD
  - npm install npm -g
  - npm prune
  - npm install

build_script:
  - node --version
  - npm --version
  - npm run build
  - npm prune --production
  - ./node_modules/electron-packager/cli.js ./ postgis-editor --out=./releases --platform=win32 --arch=x64 --icon=./postgis-editor.build-icns --overwrite --asar --prune

test: off
